site_name: "Aleksandr Michuda"

nav:
  - Home: index.md
  - Research: 
    - Published Works: research/published.md
    - Working Papers/Ongoing Projects: research/working.md
    - Book Chapters: research/chapters.md
  - Experience: 
    - experience.md
  - Transparency and Reproducibility: 
    - bitss.md
  - Teaching:
    - teaching/teaching.md
  - Software:
    - software.md

extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf_export.css

theme:
  palette:
    scheme: default
    primary: blue grey
    accent: indigo
  features:
    - navigation.tabs
    - navigation.instant
  name: material
  custom_dir: overrides
  font: 
    text: Raleway

google_analytics:
  - UA-178740663-1
  - auto

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amichuda
      name: My Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aleksandr-michuda-3a839b149/
      name: My Linkedin
    - icon: fontawesome/regular/envelope
      link: mailto:<amichuda@ucdavis.edu>
      name: Email me!
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/econaleks
      name: Follow me on Twitter!

markdown_extensions:
  - attr_list
  - admonition
  - meta
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# plugins:
#   - search
#   - pdf-export

