# This is a basic workflow to help you get started with Actions

name: CV Compile Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Convert with pandoc
        uses: docker://amichuda/pandoc-latex-extra:latest
        with:
          args: >-
            --from=markdown+raw_attribute
            --to=latex
            --output=docs/cv/aleksandr_michuda_cv.pdf
            --include-in-header=docs/cv/template.tex
            docs/cv/cv.md
      - name: setup git config
        run: |
          git config user.name "CV PDF Bot"
          git config user.email "<>"
      - name: Commit to master
        run: |
          git add docs/cv/aleksandr_michuda_cv.pdf
          git commit -m "Compiled CV"
          git push origin master
          
