# This is a basic workflow to help you get started with Actions

name: CV Compile Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  pandoc_docker_with_extra_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Modified Pandoc Docker File
        uses: docker/build-push-action@v2
        with:
          context:
          file: ./Dockerfile
          tags: pandoc_with_latex_extra:latest
          outputs: type=docker,dest=/tmp/pandoc_with_latex_extra.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pandoc_with_latex_extra
          path: /tmp/pandoc_with_latex_extra.tar
  convert_via_pandoc:
    runs-on: ubuntu-latest
    needs: pandoc_docker_with_extra_latex
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with: 
          name: pandoc_with_latex_extra
          path: /tmp
      - name: Convert with pandoc
        uses: docker://tmp/pandoc_with_latex_extra
        with:
          args: >-
            --from=markdown+raw_attribute
            --to=latex
            --output=docs/cv/aleksandr_michuda_cv.pdf
            --include-in-header=docs/cv/template.tex
            docs/cv/cv.md
