# This is a basic workflow to help you get started with Actions

name: CV Compile Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd docs/cv
      - uses: docker://pandoc/core:2.11.1
        with:
          args: >-
            --from=markdown+raw_attribute
            --to=latex
            --output=aleksandr_michuda_cv.pdf
            --include-in-header=template.tex
            cv.md
